modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/TathanDev/SkyAesthetics/issues"
license = "Insert License Here"

[[mods]]
modId = "sky_aesthetics"
version = "${version}"
displayName = "Sky Aesthetics"
authors = "TATHAN"
description = '''
Change the skybox of Minecraft like you want !
'''
#logoFile = ""

[[dependencies.sky_aesthetics]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sky_aesthetics]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "sky_aesthetics.mixins.json"
